name: Pipeline Deployment
description: Annotates the build with a file count
author: https://github.com/debora-caylent
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false